### PR TITLE
update sppull to 2.5.1

### PR DESCRIPTION
**Pull request by tknaller**

### CODE REVIEW

**Comment by chrishasz** [comment]
Thanks @tknaller

**Comment by tknaller** [comment]
thank you very much for accepting my pull request. can you update the extension on the vscode marketplace?

**Comment by chrishasz** [comment]
yes, I will release this today.

**Comment by tknaller** [comment]
awesome thank you

**Comment by chrishasz** [comment]
I just published SPGo 1.4.5 to the Marketplace.

**Pull request merged**
